language: python
sudo: false
cache: pip
dist: trusty

matrix:
  fast_finish: true

install:
  - "pip install --upgrade pip pipenv pytest==4.5.0 pytest-cov pytest-xdist==1.28 pytest-timeout"
  - "pipenv install --dev"
script:
    - "pipenv run pytest -v tests/"

jobs:
  include:
    - stage: test
      python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "2.7"
    - python: "3.5"
    - stage: packaging
      python: "3.6"
      install:
        - "pip install --upgrade twine readme-renderer[md]"
      script:
        - "python setup.py sdist"
        - "twine check dist/*"
    - stage: coverage
      python: "3.6"
      install:
        - "pip install --upgrade pip pipenv pytest==4.5.0 pytest-cov pytest-xdist==1.28 pytest-timeout"
        - "pipenv install --dev"
      script:
        - "pipenv run pytest --timeout 300 --cov=vistir --cov-report=term-missing --cov-report=xml --cov-report=html tests"
